import Head from "next/head";

export default function Layout(props) {
  console.log(props);
  return (
    <div>
      <Head>
        <title>{props.title} | Coffee Mate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {props.children}
    </div>
  );
}
